/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 2
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"

        tf:
            odom_frame: "camera_init"       # parent frame for odometry
            body_frame: "body"              # child frame

        common:
            lid_topic:  "/sensor/lidar/livox_mid360/points"
            imu_topic:  "/sensor/ins/livox_mid360/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

        preprocess:
            lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for any other pointcloud input
            scan_line:  4
            blind: 0.5
            timestamp_unit: 3
            scan_rate: 10

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     100.0
            extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
            extrinsic_R: [ 1., 0., 0.,
                            0., 1., 0.,
                            0., 0., 1.]

        publish:
            scan_bodyframe_pub_en: true  # point cloud in body-frame (required for localization)
            path_en: true                # path visualization
            map_en: false                # map visualization (disable for localization mode)
            scan_publish_en: false       # point cloud in world-frame (disable for localization mode)
            effect_map_en: false         # ICP effective points
            dense_publish_en: true       # dense vs sparse point cloud output

        pcd_save:
            pcd_save_en: true
            interval: -1                 # how many LiDAR frames saved in each pcd file;
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
            save_path: ""                # Empty: use default path (ROOT_DIR/PCD/scans.pcd). If specified, save to this path on shutdown.
            filter_size: 0.1             # Voxel size for saved map (meters). 0.1 = dense, 0 = no filter (very large file)